# Generated by Django 4.1.7 on 2023-03-08 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('anio', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('genero', models.CharField(max_length=255)),
            ],
        ),
    ]
